spring:
  jpa:
    hibernate:
      ddl-auto: none
      order_inserts: true
      order_updatest: true
      jdbc:
        batch_size: 4
    generate-ddl: false
    show-sql: true
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
